CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY NOT NULL,
    uid VARCHAR(255) NOT NULL,
	 username VARCHAR(255) NOT NULL,
	 email VARCHAR(255) NOT NULL,
	 is_verify_email BOOLEAN NOT NULL DEFAULT 'f',
	 password VARCHAR(255) NOT NULL,
	 role VARCHAR(255) NOT NULL DEFAULT 'user'
);