basePath: /
definitions:
  appl_row.AuthUser:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  appl_row.CheckEmailExist:
    properties:
      email:
        type: string
    type: object
  appl_row.CheckUsernameExist:
    properties:
      username:
        type: string
    type: object
  appl_row.CreateUser:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  appl_row.RecoveryPassword:
    properties:
      password:
        type: string
      uid:
        type: string
    type: object
  appl_row.RecoveryPasswordSendMessage:
    properties:
      email:
        type: string
    type: object
  appl_row.ValidateEmail:
    properties:
      email:
        type: string
    type: object
  appl_row.ValidatePassword:
    properties:
      password:
        type: string
    type: object
  appl_row.ValidateUsername:
    properties:
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for NFC-cash Application
  title: NFC-cash backend
  version: "1.0"
paths:
  /auth/check-email-exist:
    post:
      consumes:
      - application/json
      description: check email exist
      operationId: check-email-exist
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckEmailExist'
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckEmailExist
      tags:
      - auth
  /auth/check-username-exist:
    post:
      consumes:
      - application/json
      description: check username exist
      operationId: check-username-exist
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckUsernameExist'
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckUsernameExist
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.AuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: SignUp
      tags:
      - auth
  /recovery/recoveryPassword:
    post:
      consumes:
      - application/json
      description: recovery password
      operationId: recovery-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.RecoveryPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: RecoveryPassword
      tags:
      - recovery
  /recovery/recoveryPasswordSendMessage:
    post:
      consumes:
      - application/json
      description: recovery passwordSendMessage
      operationId: recovery-passwordSendMessage
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.RecoveryPasswordSendMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: RecoveryPasswordSendMessage
      tags:
      - recovery
  /validate/validateEmail:
    post:
      consumes:
      - application/json
      description: validate email
      operationId: validate-email
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidateEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidateEmail
      tags:
      - validate
  /validate/validatePassword:
    post:
      consumes:
      - application/json
      description: validate password
      operationId: validate-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidatePassword
      tags:
      - validate
  /validate/validateUsername:
    post:
      consumes:
      - application/json
      description: validate username
      operationId: validate-username
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidateUsername'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidateUsername
      tags:
      - validate
  /verify/emailver/:uid:
    get:
      consumes:
      - application/json
      description: verify email
      operationId: verify-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: VerifyEmail
      tags:
      - verify
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
