basePath: /
definitions:
  appl_row.AuthUser:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  appl_row.CheckConfirmAccount:
    properties:
      username:
        type: string
    type: object
  appl_row.CheckEmailExist:
    properties:
      email:
        type: string
    type: object
  appl_row.CheckRecoveryPassword:
    properties:
      uid:
        type: string
    type: object
  appl_row.CheckUsernameExist:
    properties:
      username:
        type: string
    type: object
  appl_row.CompleteRecoveryPassword:
    properties:
      uid:
        type: string
    type: object
  appl_row.CreateUser:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  appl_row.RecoveryPassword:
    properties:
      password:
        type: string
      uid:
        type: string
    type: object
  appl_row.RecoveryPasswordCompare:
    properties:
      password:
        type: string
      uid:
        type: string
    type: object
  appl_row.RecoveryPasswordSendMessage:
    properties:
      email:
        type: string
    type: object
  appl_row.ValidateEmail:
    properties:
      email:
        type: string
    type: object
  appl_row.ValidatePassword:
    properties:
      password:
        type: string
    type: object
  appl_row.ValidateUsername:
    properties:
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for NFC-cash Application
  title: NFC-cash backend
  version: "1.0"
paths:
  /auth/check-confirm-account:
    post:
      consumes:
      - application/json
      description: check confirm account
      operationId: check-confirm-account
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckConfirmAccount'
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckConfirmAccount
      tags:
      - auth
  /auth/check-email-exist:
    post:
      consumes:
      - application/json
      description: check email exist
      operationId: check-email-exist
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckEmailExist'
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckEmailExist
      tags:
      - auth
  /auth/check-username-exist:
    post:
      consumes:
      - application/json
      description: check username exist
      operationId: check-username-exist
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckUsernameExist'
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckUsernameExist
      tags:
      - auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.AuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: SignUp
      tags:
      - auth
  /recovery-password-compare:
    post:
      consumes:
      - application/json
      description: recovery password compare
      operationId: recovery-password-compare
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.RecoveryPasswordCompare'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: RecoveryPasswordCompare
      tags:
      - recovery
  /recovery-password-complete:
    post:
      consumes:
      - application/json
      description: complete recovery password
      operationId: complete-recovery-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CompleteRecoveryPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CompleteRecoveryPassword
      tags:
      - recovery
  /recovery/check-recovery-password:
    post:
      consumes:
      - application/json
      description: check recovery password
      operationId: check-recovery-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.CheckRecoveryPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckRecoveryPassword
      tags:
      - recovery
  /recovery/recovery-password:
    post:
      consumes:
      - application/json
      description: recovery password
      operationId: recovery-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.RecoveryPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: RecoveryPassword
      tags:
      - recovery
  /recovery/recovery-password-send-message:
    post:
      consumes:
      - application/json
      description: recovery password send message
      operationId: recovery-password-send-message
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.RecoveryPasswordSendMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: RecoveryPasswordSendMessage
      tags:
      - recovery
  /user/get-user-profile:
    get:
      consumes:
      - application/json
      description: get user profile
      operationId: get-user-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: GetUserProfile
      tags:
      - user
  /validate/validate-email:
    post:
      consumes:
      - application/json
      description: validate email
      operationId: validate-email
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidateEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidateEmail
      tags:
      - validate
  /validate/validate-password:
    post:
      consumes:
      - application/json
      description: validate password
      operationId: validate-password
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidatePassword
      tags:
      - validate
  /validate/validate-username:
    post:
      consumes:
      - application/json
      description: validate username
      operationId: validate-username
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/appl_row.ValidateUsername'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: ValidateUsername
      tags:
      - validate
  /verify/check-email-verify:
    post:
      consumes:
      - application/json
      description: check email verify
      operationId: check-email-verify
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: CheckEmailVerify
      tags:
      - checkEmailVerify
  /verify/emailver/:uid:
    get:
      consumes:
      - application/json
      description: verify email
      operationId: verify-email
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
        default:
          description: ""
          schema: {}
      summary: VerifyEmail
      tags:
      - verify
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
